name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.1
        with:
          gradle-version: 6.9.4
          add-job-summary: never

      - name: Build with Gradle
        run: gradle build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: skidbounce
          path: build/libs/skidbounce-v?.?.?.jar
          if-no-files-found: error
